# Fill-in tutorial controls
# LEVEL: 01-08
# TRACK: starter|solution
LEVEL := 01
TRACK := starter

###############################################
###############################################
###############################################

GPU := H100
SRC := level_$(LEVEL)_$(TRACK).cu
OUT := level_$(LEVEL)_$(TRACK).out
CMD := ./level_$(LEVEL)_$(TRACK).out
CONFIG := standalone
include ../../../kernels/common.mk
